import React from 'react';
import { Asset, User, Role, Loan, LoanStatus } from './types';

export const COLORS = {
  primary: '#b91c1c',
  secondary: '#ca8a04',
  accent: '#1e293b'
};

export const TRANSLATIONS: Record<string, any> = {
  id: {
    welcome: "Selamat Datang!",
    loginDesc: "Pengelolaan, pemantauan, dan peminjaman alat laboratorium Laboratorium Fakultas Ilmu Terapan Telkom University",
    usernameLabel: "Username",
    passwordLabel: "Kata Sandi",
    loginBtn: "Masuk",
    rememberMe: "Ingat saya",
    forgotPass: "Lupa Kata Sandi?",
    register: "Registrasi",
    logout: "Keluar",
    home: "Beranda",
    labs: "Laboratorium",
    inventory: "Semua Aset",
    adminAssets: "Aset Admin",
    manageAssets: "Kelola Aset",
    addAsset: "Tambah Alat Baru",
    loans: "Persetujuan",
    monitoring: "Monitoring",
    admin: "Panel Kontrol",
    profile: "Profil Saya",
    scanBtn: "Pindai QR",
    scanTitle: "Pindai Kode QR Aset",
    scanDesc: "Arahkan kamera ke kode QR yang tertempel di alat",
    searchPlaceholder: "Cari alat...",
    borrowBtn: "Pinjam Alat",
    available: "Tersedia",
    borrowed: "Dipinjam",
    maintenance: "Maintenance",
    history: "Riwayat",
    historyTitle: "RIWAYAT PEMINJAMAN", 
    archiveSystem: "Sistem Arsip", 
    records: "data", 
    exportBtn: "Ekspor ke Excel", 
    assetTable: "User & Alat", 
    statusTable: "Status", 
    dateTable: "Waktu Kembali", 
    asset: "Aset",
    borrowerInfo: "Info Peminjam",
    time: "Waktu",
    status: "Status",
    action: "Aksi",
    returnBtn: "Kembalikan",
    totalAsset: "Total Aset",
    pendingApproval: "Persetujuan Peminjaman",
    approve: "Setujui",
    reject: "Tolak",
    printLabel: "Cetak Label QR",
    formTitle: "Form Peminjaman Alat",
    deadlineWarning: "Peringatan: Alat wajib dikembalikan ke Laboran sebelum jam 18:00 WIB di hari yang sama.",
    studentNim: "NIM",
    class: "Kelas",
    borrowDate: "Tanggal Pinjam",
    borrowTime: "Jam Pinjam", 
    reason: "Alasan",
    cancel: "Batal",
    submitRequest: "Kirim",
    saveAsset: "Simpan Aset",
    assetName: "Nama Alat",
    category: "Kategori",
    location: "Lokasi",
    close: "Tutup",
    simScan: "Simulasi Pindai",
    back: "Kembali",
    empty: "Kosong",
    noData: "TIDAK ADA ALAT YANG SEDANG DIPINJAM", 
    adminRoom: "Ruang Admin",
    fullNameLabel: "Nama Lengkap",
    phoneNumberLabel: "Nomor HP",
    roleLabel: "Peran / Role",
    confirmPasswordLabel: "Konfirmasi Kata Sandi",
    registerBtn: "Kirim Data Registrasi",
    backToLogin: "Kembali ke Login",
    exploreBtn: "Eksplorasi",
    recentActivity: "Aktivitas Terakhir",
    noRecentData: "Belum ada data",
    statusLabel: "Status",
    labListTitle: "Daftar Laboratorium",
    labListDesc: "Pilih laboratorium untuk melihat detail aset yang tersedia",
    roomLabel: "Ruangan",
    viewAsset: "Lihat Aset",
    backToList: "Kembali ke Daftar",
    labInventory: "Inventaris Aset Laboratorium",
    noAssetInLab: "Belum ada aset terdaftar di lab ini",
    adminInventoryTitle: "Inventaris Aset Admin",
    manageAssetTitle: "Kelola Data Aset",
    searchAssetPlaceholder: "Cari nama atau kode aset...",
    allFilter: "Semua",
    noCategory: "Tanpa Kategori",
    dataNotFound: "Data Tidak Found",
    editBtn: "Edit",
    catIT: "Perangkat IT & Komputasi",
    catNet: "Perangkat Jaringan & Telekomunikasi",
    catIoT: "Perangkat Elektronika & IoT",
    catLab: "Peralatan Laboratorium & Pengukuran",
    catDoc: "Aset Dokumen & Administrasi",
    catSec: "Perangkat Keamanan & Kontrol Akses",
    catOther: "Aset Non-Teknis tapi Bernilai",
    editAssetTitle: "Edit Data Aset",
    regAssetTitle: "Registrasi Aset",
    editAssetDesc: "Perbarui informasi inventaris resmi",
    regAssetDesc: "Input data inventaris resmi laboratorium",
    secIdentity: "1. Identitas Dasar Alat",
    secProcurement: "2. Legalitas & Pengadaan",
    secPlacement: "3. Penempatan & Kondisi",
    secSpec: "4. Spesifikasi & Pendukung",
    assetBrand: "Merk & Tipe",
    serialNumberLabel: "Nomor Seri (SN)",
    procurementYearLabel: "Tahun Perolehan",
    fundingSourceLabel: "Sumber Pendanaan",
    invoiceNumberLabel: "Nomor Invoice",
    selectCategory: "Pilih Kategori Aset",
    specificLocationLabel: "Lokasi Spesifik",
    conditionBaik: "Kondisi: Baik",
    conditionRusakRingan: "Rusak Ringan",
    conditionRusakBerat: "Rusak Berat",
    picLabel: "Nama PIC/Laboran",
    descPlaceholder: "Deskripsi Spesifikasi Teknis...",
    accessoriesPlaceholder: "Kelengkapan/Aksesoris",
    qrHelper: "Isi Nama & SN untuk QR",
    printBtn: "Cetak Label (Direct)",
    photoLabel: "Foto Utama & Label Spek",
    manualBookLabel: "Manual Book (Digital)",
    updateAssetBtn: "Update Aset",
    saveAssetBtn: "Simpan Aset",
    practicumModule: "Modul Praktikum",
    electronicPart: "Komponen Elektronika",
    approvalTitle: "Persetujuan Peminjaman",
    approvalDesc: "Konfirmasi permintaan penggunaan aset",
    thApplicant: "Pemohon",
    thAssetQty: "Aset & Qty",
    thBorrowTime: "Waktu Pinjam", 
    thStatus: "Status",
    thAction: "Aksi",
    qtyLabel: "Jumlah",
    noApprovalQueue: "Tidak ada antrian persetujuan",
    approveBtn: "Setujui",
    rejectBtn: "Tolak",
    statusPending: "MENUNGGU",
    statusApproved: "DISETUJUI",
    statusRejected: "DITOLAK",
    monitoringTitle: "Monitoring Aset",
    thBorrower: "Peminjam",
    thDeviceInfo: "Informasi Alat",
    thReturnEst: "Estimasi Kembali",
    thStatusAction: "Status Aksi",
    noActiveLoan: "TIDAK ADA ALAT YANG SEDANG DIPINJAM",
    confirmReturnBtn: "Konfirmasi Kembali",
    confirmReturnAlert: "Konfirmasi pengembalian alat: ",
    confirmReturnSubAlert: "? Status alat akan kembali menjadi TERSEDIA.",
    
    // --- KATA KUNCI BARU TAMBAHAN ---
    systemSubtitle: "Sistem Monitoring Aset",
    logisticSummary: "Ringkasan Data Logistik",
    fileShortcut: "Pintasan Berkas",
    guideTitle: "Panduan Pengguna",
    guideDesc: "Butuh bantuan operasional laboratorium? Unduh modul tata cara peminjaman alat di sini.",
    openDocBtn: "Buka Dokumen",
    userLabel: "Mahasiswa",
    loanActionLabel: "mengajukan alat",
    timeAgo: "Baru saja",
    noRecentDataDesc: "Mulai eksplorasi daftar laboratorium untuk melihat log atau mengajukan surat izin peminjaman alat."
  },

  en: {
    welcome: "Welcome!",
    loginDesc: "Management, monitoring, and borrowing of laboratory equipment at the Faculty of Applied Sciences, Telkom University",
    usernameLabel: "Username",
    passwordLabel: "Password",
    loginBtn: "Login",
    rememberMe: "Remember me",
    forgotPass: "Forgot Password?",
    register: "Register",
    logout: "Logout",
    home: "Home",
    labs: "Laboratories",
    inventory: "All Assets",
    adminAssets: "Admin Assets",
    manageAssets: "Manage Assets",
    addAsset: "Add New Item",
    loans: "Approvals",
    monitoring: "Monitoring",
    admin: "Control Panel",
    profile: "My Profile",
    scanBtn: "Scan QR",
    scanTitle: "Scan Asset QR Code",
    scanDesc: "Point camera at the QR code attached to the equipment",
    searchPlaceholder: "Search equipment...",
    borrowBtn: "Borrow Equipment",
    available: "Available",
    borrowed: "Borrowed",
    maintenance: "Maintenance",
    history: "History",
    historyTitle: "LOAN HISTORY", 
    archiveSystem: "Archive System", 
    records: "records", 
    exportBtn: "Export to Excel", 
    assetTable: "User & Asset", 
    statusTable: "Status", 
    dateTable: "Returned At", 
    asset: "Asset",
    borrowerInfo: "Borrower Info",
    time: "Time",
    status: "Status",
    action: "Action",
    returnBtn: "Return",
    totalAsset: "Total Assets",
    pendingApproval: "Loan Approvals",
    approve: "Approve",
    reject: "Reject",
    printLabel: "Print QR Label",
    formTitle: "Equipment Loan Form",
    deadlineWarning: "Warning: Equipment must be returned to the Technician before 6:00 PM on the same day.",
    studentNim: "NIM / Student ID",
    class: "Class",
    borrowDate: "Borrow Date",
    borrowTime: "Borrow Time",
    reason: "Reason",
    cancel: "Cancel",
    submitRequest: "Submit",
    saveAsset: "Save Asset",
    assetName: "Item Name",
    category: "Category",
    location: "Location",
    close: "Close",
    simScan: "Simulate Scan",
    back: "Back",
    empty: "Empty",
    noData: "NO EQUIPMENT CURRENTLY BORROWED", 
    adminRoom: "Admin Room",
    fullNameLabel: "Full Name",
    phoneNumberLabel: "Phone Number",
    roleLabel: "Role",
    confirmPasswordLabel: "Confirm Password",
    registerBtn: "Submit Registration",
    backToLogin: "Back to Login",
    exploreBtn: "Explore",
    recentActivity: "Recent Activity",
    noRecentData: "No data available",
    statusLabel: "Status",
    labListTitle: "Laboratory List",
    labListDesc: "Select a laboratory to view available asset details",
    roomLabel: "Room",
    viewAsset: "View Assets",
    backToList: "Back to List",
    labInventory: "Laboratory Asset Inventory",
    noAssetInLab: "No assets registered in this lab yet",
    adminInventoryTitle: "Admin Asset Inventory",
    manageAssetTitle: "Manage Asset Data",
    searchAssetPlaceholder: "Search asset name or code...",
    allFilter: "All",
    noCategory: "No Category",
    dataNotFound: "Data Not Found",
    editBtn: "Edit",
    catIT: "IT & Computing Devices",
    catNet: "Networking & Telecom Devices",
    catIoT: "Electronics & IoT Devices",
    catLab: "Laboratory & Measuring Tools",
    catDoc: "Document & Admin Assets",
    catSec: "Security & Access Control",
    catOther: "Non-Technical Valuable Assets",
    editAssetTitle: "Edit Asset Data",
    regAssetTitle: "Asset Registration",
    editAssetDesc: "Update official inventory information",
    regAssetDesc: "Input official laboratory inventory data",
    secIdentity: "1. Basic Device Identity",
    secProcurement: "2. Legality & Procurement",
    secPlacement: "3. Placement & Condition",
    secSpec: "4. Specifications & Support",
    assetBrand: "Brand & Type",
    serialNumberLabel: "Serial Number (SN)",
    procurementYearLabel: "Procurement Year",
    fundingSourceLabel: "Funding Source",
    invoiceNumberLabel: "Invoice Number",
    selectCategory: "Select Asset Category",
    specificLocationLabel: "Specific Location",
    conditionBaik: "Condition: Good",
    conditionRusakRingan: "Minor Damage",
    conditionRusakBerat: "Major Damage",
    picLabel: "PIC/Technician Name",
    descPlaceholder: "Technical Specification Description...",
    accessoriesPlaceholder: "Accessories/Completeness",
    qrHelper: "Enter Name & SN for QR",
    printBtn: "Print Label (Direct)",
    photoLabel: "Main Photo & Spec Label",
    manualBookLabel: "Manual Book (Digital)",
    updateAssetBtn: "Update Asset",
    saveAssetBtn: "Save Asset",
    practicumModule: "Practicum Module",
    electronicPart: "Electronic Components",
    approvalTitle: "Loan Approval",
    approvalDesc: "Confirm asset usage requests",
    thApplicant: "Applicant",
    thAssetQty: "Asset & Qty",
    thBorrowTime: "Borrow Time",
    thStatus: "Status",
    thAction: "Action",
    qtyLabel: "Quantity",
    noApprovalQueue: "No approval queue found",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    statusPending: "PENDING",
    statusApproved: "APPROVED",
    statusRejected: "REJECTED",
    monitoringTitle: "Asset Monitoring",
    thBorrower: "Borrower",
    thDeviceInfo: "Device Information",
    thReturnEst: "Return Estimation",
    thStatusAction: "Status Action",
    noActiveLoan: "NO DEVICES CURRENTLY ON LOAN",
    confirmReturnBtn: "Confirm Return",
    confirmReturnAlert: "Confirm return for: ",
    confirmReturnSubAlert: "? Asset status will revert to AVAILABLE.",
    
    // --- KATA KUNCI BARU TAMBAHAN ---
    systemSubtitle: "Asset Monitoring System",
    logisticSummary: "Logistics Data Summary",
    fileShortcut: "File Shortcuts",
    guideTitle: "User Guide",
    guideDesc: "Need laboratory operational help? Download the equipment loan procedure module here.",
    openDocBtn: "Open Document",
    userLabel: "Student",
    loanActionLabel: "requested an asset",
    timeAgo: "Just now",
    noRecentDataDesc: "Start exploring the laboratory list to view logs or submit equipment loan applications."
  }
};

export const INITIAL_ASSETS: Asset[] = [];

export const INITIAL_LOANS: Loan[] = [];